dist: xenial
language: node_js
node_js:
  - lts/boron # v6
  - lts/carbon # v8
  - lts/dubnium # v10
  - lts/*
  - node
cache: npm
deploy:
  provider: npm
  email: axel@havukangas.fi
  api_key:
    secure: eraPidAwjsGkPRHGODZxPaVJr4caQKPFbfZGQ04r8vbA2DqHC4i6amTImxvWGAAaadxnO2cncPYUU+LeAx/iAQ/LEpH2SGGJ0SmHRZ2clGXd59eies4VW0HH8Yf/6/YsVFfMZx17JW5puI8Ig3Sj20S/CaiCklKwi2peM68YxOaLsSiFVErnzkeApGQeEvJXcoyp2xSTtJsZw5hR7NnrH2XvMWtFz3Yvo9Z1sgOjdoisPTK0XL18qWSD45loasCIxVUZRFmm2mDUF97jEN5sZO5z+0V2hM4J9/e670fROQe82/02bIdske6LaqhGxRy60BY+c6NR5+2jw/bqCyNlQxW0T1pl3nlEGWWCg+hY0rroQdXdFEDyUm5uGsKYQpy/tL6szrp6p4l2BXJ0dhV8qNnKX5CldKb8GyuVLjFF5mD7XuUqOY/hj8JR7Hqh8n9PJ9I6uv4QWRUWlciFswm0k+9tTQAxqTlqqFvfzy169yPQAkO7gIvdKv4vvNm2zs5v85Lq/K/mDVdak1AbuWIr5TQLwwREgk9h7XVfuF49YAm9pJvkQfv/ifxml9cgdYDcxdUvzfsq+pvnQpdCSDUlx1lpB50XZlPdq7Ps/EDL4Ph7sumMMxiA3QHLQpySR+NMHNo2zEpWGSYb0vlhgOuVrabVteccuAp8gqwP/1dj/Es=
  skip_cleanup: true
  on:
    tags: true
    repo: aeirola/io-ts-promise
